### ISSUE TITLE
Project roadmap

### ISSUE THREAD

**Issue by clovisdasilvaneto** [clovisdasilvaneto/jack-assistant#1]
- [ ] Create github repo
- [ ] Understand jack methodology
- [ ] Create brain functions
- [ ] Initialise brain functions on orchestrator
