### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by clovisdasilvaneto** [clovisdasilvaneto/jack-assistant#1]
### Initial setup
- [x] Create github repo
- [x] Understand jack methodology
- [x] Create brain functions
- [x] Initialise brain functions on orchestrator

### Create temporal functions
- [ ] Speak
- [ ] Listen
- [ ] State

### Create jack state
- [ ] Load
- [ ] Save
- [ ] Use it on orchestrator ( ? )

### Create Natural Language function
- TBD
